import re
import csv
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# --- Configuration ---
# ... (rest of the file)


# --- Configuration ---
# The final, sorted log file generated by `run_full_test.py`
MERGED_LOG_FILE = 'merged_test_run.log'
# The output CSV file
OUTPUT_CSV_FILE = 'performance_analysis.csv'

# --- Event Definitions ---
# This is the core logic. We define rules to identify the start and end of each event
# we want to measure. Each rule contains:
# - 'event_name': The name that will appear in the CSV.
# - 'start_regex': A regex to find the log line that starts the event.
# - 'end_regex': A regex to find the log line that ends the event.
# - 'id_regex': (Optional) A regex to extract a unique ID to match start/end pairs (e.g., a task ID).

# This regex will match either a UUID or a LONG_TASK_ID
# e.g., "686a6bf9-8cfb-4088-a492-06f8b3b50a2b" or "LONG_TASK_1"
UUID_OR_LONG_TASK_REGEX = r'(?:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}|LONG_TASK_\d+)'
THREAD_ID_REGEX = r'\d+\s+\d+' # Captures the two numbers representing thread IDs

EVENT_RULES = [
    {
        # Measures the full round-trip time from the client's perspective for a long task.
        'event_name': 'CLIENT_ROUND_TRIP_LONG_TASK',
        'start_regex': r'\[CLIENT\] \[(LONG_TASK_\d+)\] ---> Sending request...',
        # This end event is tricky because the final response is polled for, not directly received.
        # We will use the "Task complete!" log from the client polling script.
        'end_regex': r'\[CLIENT\] \[(LONG_TASK_\d+)\].*Task complete!',
        'id_regex': r'(LONG_TASK_\d+)'
    },
    {
        # Measures the time from when a client sends a request until the server
        # assigns it a UUID and logs that it has started handling the request.
        'event_name': 'NETWORK_LATENCY_AND_SERVER_ACCEPTANCE',
        'start_regex': r'\[CLIENT\] \[(LONG_TASK_\d+)\] ---> Sending request...',
        # This now correctly looks for the server's initial handling log.
        'end_regex': r'\[SERVER\].* I TestServer: Handling: POST /recognize for task (' + UUID_OR_LONG_TASK_REGEX + r')',
        'is_linking_rule': True
        # A better metric is to measure from when the server starts handling to when it queues.
    },
    {
        # This now specifically measures the artificial delay period for testing.
        'event_name': 'SERVER_ARTIFICIAL_DELAY',
        'start_regex': r'\[SERVER\].*\[(' + UUID_OR_LONG_TASK_REGEX + r')\] - Starting 8-second artificial delay',
        'end_regex': r'\[SERVER\].*I ImageRecognizer: Detection complete.', # Ends when detection is done
        'id_regex': None
    },
    {
        # Measures the time from when the model finishes to when the server releases the permit.
        # This captures the final result handling and cleanup.
        'event_name': 'SERVER_RESULT_HANDLING_TIME',
        'start_regex': r'\[SERVER\].*\[(' + UUID_OR_LONG_TASK_REGEX + r')\] - Recognition successful',
        'end_regex': r'\[SERVER\].*\[(' + UUID_OR_LONG_TASK_REGEX + r')\] - Permit released, task finished',
        'id_regex': r'(' + UUID_OR_LONG_TASK_REGEX + r')'
    },
    {
        # Measures the core ML model inference time inside the ImageRecognizer.
        'event_name': 'RECOGNIZER_DETECTION_TIME',
        # CORRECTED: The actual work starts AFTER the artificial delay.
        'start_regex': r'\[SERVER\].*\[(' + UUID_OR_LONG_TASK_REGEX + r')\] - Artificial delay finished\. Starting actual work\.',
        'end_regex': r'\[SERVER\].*I ImageRecognizer: Detection complete.',
        'id_regex': None
    },


    # --- NEW, MORE PRECISE RULES START HERE ---
    {
        # Measures the time from when a task is queued until it acquires a permit to run.
        'event_name': 'SERVER_PERMIT_WAIT_TIME',
        'start_regex': r'\[SERVER\].*\[(' + UUID_OR_LONG_TASK_REGEX + r')\] - Task is now waiting for a permit',
        'end_regex': r'\[SERVER\].*\[(' + UUID_OR_LONG_TASK_REGEX + r')\] - Permit acquired',
        'id_regex': r'(' + UUID_OR_LONG_TASK_REGEX + r')'
    },
    {
        # Measures the time it takes to save the recognition result to the database.
        'event_name': 'RECOGNIZER_DB_SAVE_TIME',
        'start_regex': r'\[SERVER\].*I ImageRecognizer: Detection complete.',
        'end_regex': r'\[SERVER\].*I ImageRecognizer: Recognition result saved to database.',
        'id_regex': None # This is a global, non-task-specific event
    },
    {
        # Measures the time it takes for the ObjectDetector to close after saving the result.
        'event_name': 'RECOGNIZER_CLEANUP_TIME',
        'start_regex': r'\[SERVER\].*I ImageRecognizer: Recognition result saved to database.',
        'end_regex': r'\[SERVER\].*I ImageRecognizer: ObjectDetector has been closed.',
        'id_regex': None # This is also a global, non-task-specific event
    }


]





# Regex to capture the timestamp from any merged log line
TIMESTAMP_REGEX = re.compile(r'(\d{2}:\d{2}:\d{2}\.\d{3})')

def parse_line(line):
    """Parses a single line from the merged log file to extract its timestamp and content."""
    match = TIMESTAMP_REGEX.search(line)
    if not match:
        return None, None

    timestamp_str = match.group(1)
    try:
        # We only need the time part for duration calculation
        dt_obj = datetime.strptime(timestamp_str, '%H:%M:%S.%f')
        return dt_obj, line
    except (ValueError, IndexError):
        return None, None

# def plot_gantt_chart(completed_events, output_filename='performance_gantt.png'):
#     """
#     Generates and saves a Gantt chart where each row is an EVENT TYPE,
#     showing when each event occurs over the total timeline.
#     """
#     if not completed_events:
#         return

#     print(f"\nGenerating event-oriented Gantt chart and saving to '{output_filename}'...")

#     # # --- 1. Data and Plotting Setup ---
#     # fig, gnt = plt.subplots(figsize=(20, 10))
#     # gnt.set_title('Full System Event Timeline', fontsize=16, pad=20)
#     # gnt.set_xlabel('Time (HH:MM:SS.ms)', fontsize=12)
#     # gnt.set_ylabel('Event Type', fontsize=12)
#     # gnt.grid(True, which='major', linestyle='--', alpha=0.7)
#     #
#     # # --- 2. Y-axis (Event Names) and Color Setup ---
#     # # Use all event names from the rules to ensure a consistent order and color
#     # event_names = sorted([rule['event_name'] for rule in EVENT_RULES])

#     # --- 1. Data and Plotting Setup ---
#     fig, gnt = plt.subplots(figsize=(20, 10))
#     # ... (rest of the setup)

#     # --- NEW: Filter for specific events to display ---
#     events_to_display = [
#         'SERVER_RESULT_HANDLING_TIME',
#         'SERVER_PERMIT_WAIT_TIME',
#         'SERVER_ARTIFICIAL_DELAY',
#         'RECOGNIZER_DETECTION_TIME',
#     ]
#     filtered_events = [e for e in completed_events if e['Event Name'] in events_to_display]

#     if not filtered_events:
#         print("\nWarning: None of the specified events for the Gantt chart were found in the completed events.")
#         return
#     # --- END NEW ---

#     # --- 2. Y-axis (Event Names) and Color Setup ---
#     # Use the filtered list of event names to build the y-axis
#     event_names = sorted(events_to_display)
#     # ... (the rest of the function remains the same)

#     y_ticks = [10 * (i + 1) for i in range(len(event_names))]
#     gnt.set_yticks(y_ticks)
#     gnt.set_yticklabels(event_names)
#     gnt.set_ylim(0, 10 * (len(event_names) + 1))

#     colors = plt.cm.get_cmap('tab20', len(event_names))
#     color_map = {name: colors(i) for i, name in enumerate(event_names)}

#     # Create a map from event name to its y-axis position
#     event_y_pos_map = {name: y_ticks[i] for i, name in enumerate(event_names)}

#     # --- 3. Plotting all Completed Events ---
#     for event in completed_events:
#         event_name = event['Event Name']
#         y_pos = event_y_pos_map.get(event_name)
#         if y_pos is None: continue # Skip if event name isn't in our map

#         try:
#             start_time = datetime.strptime(event['Start Time'], '%H:%M:%S.%f')
#             end_time = datetime.strptime(event['End Time'], '%H:%M:%S.%f')
#         except ValueError:
#             continue

#         start_num = mdates.date2num(start_time)
#         end_num = mdates.date2num(end_time)
#         duration = end_num - start_num

#         # Plot the bar on the correct event-type row
#         gnt.barh(y=y_pos, width=duration, left=start_num, height=5,
#                  color=color_map.get(event_name, 'gray'),
#                  edgecolor='black', linewidth=0.5)

#         # Add the Task ID as a label on the bar
#         task_id_label = event['Event ID']
#         if task_id_label != "N/A":
#             gnt.text(start_num + duration/2, y_pos, task_id_label.replace("LONG_TASK_", ""),
#                      ha='center', va='center', color='black', fontsize=7, weight='bold')


#     # --- 4. Formatting Axes ---
#     gnt.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S.%f'))
#     gnt.xaxis.set_major_locator(plt.MaxNLocator(14))
#     plt.xticks(rotation=30, ha='right')

#     plt.tight_layout()
#     plt.savefig(output_filename, bbox_inches='tight')
#     print(f"✅ Gantt chart saved successfully to '{output_filename}'.")

def plot_gantt_chart(completed_events, output_filename='performance_gantt.png'):
    """
    Generates and saves a Gantt chart where each row is an EVENT TYPE,
    showing when each event occurs over the total timeline.
    """    
    if not completed_events:
        return

    print(f"\nGenerating event-oriented Gantt chart and saving to '{output_filename}'...")

    # --- 1. Data and Plotting Setup ---
    fig, gnt = plt.subplots(figsize=(20, 10))
    gnt.set_title('Server-Side Event Timeline', fontsize=16, pad=20)
    gnt.set_xlabel('Time (HH:MM:SS.ms)', fontsize=12)
    gnt.set_ylabel('Event Type', fontsize=12)
    gnt.grid(True, which='major', linestyle='--', alpha=0.7)

    # --- NEW: Filter for specific events to display ---
    events_to_display = [
        'SERVER_RESULT_HANDLING_TIME',
        'SERVER_PERMIT_WAIT_TIME',
        'SERVER_ARTIFICIAL_DELAY',
        'RECOGNIZER_DETECTION_TIME',
    ]
    filtered_events = [e for e in completed_events if e['Event Name'] in events_to_display]

    if not filtered_events:
        print("\nWarning: None of the specified events for the Gantt chart were found in the completed events.")
        return
    # --- END NEW ---

    # --- 2. Y-axis (Event Names) and Color Setup ---
    # Use the filtered list of event names to build the y-axis
    event_names = sorted(events_to_display)

    y_ticks = [10 * (i + 1) for i in range(len(event_names))]
    gnt.set_yticks(y_ticks)
    gnt.set_yticklabels(event_names)
    gnt.set_ylim(0, 10 * (len(event_names) + 1))

    colors = plt.cm.get_cmap('tab20', len(event_names))
    color_map = {name: colors(i) for i, name in enumerate(event_names)}

    # Create a map from event name to its y-axis position
    event_y_pos_map = {name: y_ticks[i] for i, name in enumerate(event_names)}

    # --- 3. Plotting all Completed Events ---
    for event in filtered_events:
        event_name = event['Event Name']
        y_pos = event_y_pos_map.get(event_name)
        if y_pos is None: continue # Skip if event name isn't in our map

        try:
            start_time = datetime.strptime(event['Start Time'], '%H:%M:%S.%f')
            end_time = datetime.strptime(event['End Time'], '%H:%M:%S.%f')
        except ValueError:
            continue

        start_num = mdates.date2num(start_time)
        end_num = mdates.date2num(end_time)
        duration = end_num - start_num

        # Plot the bar on the correct event-type row
        gnt.barh(y=y_pos, width=duration, left=start_num, height=5,
                 color=color_map.get(event_name, 'gray'),
                 edgecolor='black', linewidth=0.5)

        # Add the Task ID as a label on the bar
        task_id_label = event['Event ID']
        if task_id_label != "N/A":
            gnt.text(start_num + duration/2, y_pos, task_id_label.replace("LONG_TASK_", ""),
                     ha='center', va='center', color='black', fontsize=7, weight='bold')

        # --- NEW: Add Start and End Time Labels ---
        time_label_fontsize = 6
        # Add start time label just before the bar, showing seconds and milliseconds
        gnt.text(start_num, y_pos, start_time.strftime('%S.%f')[:-3],
                 ha='right', va='center', color='royalblue', fontsize=time_label_fontsize)
        # Add end time label just after the bar, showing seconds and milliseconds
        gnt.text(end_num, y_pos, end_time.strftime('%S.%f')[:-3],
                 ha='left', va='center', color='red', fontsize=time_label_fontsize)
        # --- END NEW ---

    # --- 4. Formatting Axes ---
    gnt.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S.%f'))
    gnt.xaxis.set_major_locator(plt.MaxNLocator(14))
    plt.xticks(rotation=30, ha='right')

    plt.tight_layout()
    plt.savefig(output_filename, bbox_inches='tight')
    print(f"✅ Gantt chart saved successfully to '{output_filename}'.")




def main():
    """Main function to read logs, process events, and write CSV."""
    print(f"Reading merged log file: '{MERGED_LOG_FILE}'...")
    try:
        with open(MERGED_LOG_FILE, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"ERROR: The log file '{MERGED_LOG_FILE}' was not found.")
        print("Please run 'run_full_test.py' first to generate the log file.")
        return

    # --- Build the UUID -> LONG_TASK map (Corrected Logic) ---
    print("\nBuilding mapping from UUIDs to LONG_TASK IDs...")
    uuid_to_long_task_map = {}
    link_rule = next((rule for rule in EVENT_RULES if rule.get('is_linking_rule')), None)
    if link_rule:
        # Use the corrected regexes to find all start and end IDs
        found_long_task_ids = [m.group(1) for line in lines if (m := re.search(link_rule['start_regex'], line))]
        found_uuids = [m.group(1) for line in lines if (m := re.search(link_rule['end_regex'], line))]
        # Zip them together to create the map
        # Zip them together to create the map
        for long_task_id, uuid in zip(found_long_task_ids, found_uuids):
            # The 'uuid' variable already holds the correct, full UUID.
            # The faulty re.search is removed.
            uuid_to_long_task_map[uuid] = long_task_id
            print(f"Mapping found: {uuid} -> {long_task_id}")

        print("Mapping complete.")

    # This new map will link a thread_key to a task_id at the moment a permit is acquired
    thread_to_task_map = {}

    # --- Process Events (Corrected Logic) ---
    timing_rules = [rule for rule in EVENT_RULES if not rule.get('is_linking_rule')]    
    pending_events = {rule['event_name']: {} for rule in timing_rules}
    completed_events = []

    print("\nProcessing timing events...")
    for i, line in enumerate(lines):
        thread_match = re.search(THREAD_ID_REGEX, line)
        thread_key = f"thread_{thread_match.group(0)}" if thread_match else None

        # New: When a permit is acquired, link the thread to its task ID
        if "Permit acquired" in line and thread_key:
            task_id_match = re.search(r'\[(' + UUID_OR_LONG_TASK_REGEX + r')\]', line)
            if task_id_match:
                task_id = uuid_to_long_task_map.get(task_id_match.group(1), task_id_match.group(1))
                thread_to_task_map[thread_key] = task_id


        for rule in timing_rules:
            event_name = rule['event_name']

            # --- Handle End of Event ---
            if re.search(rule['end_regex'], line):
                key_to_close = None
                id_pattern = rule.get('id_regex')
                if id_pattern and (id_match := re.search(id_pattern, line)):
                    raw_id = id_match.group(1)
                    key_to_close = uuid_to_long_task_map.get(raw_id, raw_id)

                # Fallback for events that end on a line with a thread ID but no task ID
                if not key_to_close and thread_key:
                    task_id_on_thread = thread_to_task_map.get(thread_key)
                    if task_id_on_thread and task_id_on_thread in pending_events[event_name]:
                        key_to_close = task_id_on_thread

                # Fallback for global, non-task events
                if not key_to_close:
                    global_key = f"global_{event_name}"
                    if global_key in pending_events[event_name]:
                        key_to_close = global_key

                if key_to_close and key_to_close in pending_events[event_name]:
                    start_time, start_line_num, start_event_id = pending_events[event_name].pop(key_to_close)
                    end_time, _ = parse_line(line)
                    if start_time and end_time:
                        completed_events.append({
                            'Event Name': event_name, 'Event ID': start_event_id,
                            'Start Time': start_time.strftime('%H:%M:%S.%f')[:-3],
                            'End Time': end_time.strftime('%H:%M:%S.%f')[:-3],
                            'Duration (ms)': f"{(end_time - start_time).total_seconds() * 1000:.2f}",
                            'Start Line': start_line_num + 1, 'End Line': i + 1
                        })

            # --- Handle Start of Event ---
            if re.search(rule['start_regex'], line):
                pending_key, display_id = None, "N/A"

                # Use the start_regex to find the line and potentially an ID
                if start_match := re.search(rule['start_regex'], line):

                    # LOGIC PATH 1: The rule's start_regex captures an ID (e.g., CLIENT_ROUND_TRIP, RECOGNIZER_DETECTION_TIME)
                    if start_match.groups():
                        raw_id = start_match.group(1)
                        # Always get the final LONG_TASK_# name for consistency
                        display_id = uuid_to_long_task_map.get(raw_id, raw_id)
                        pending_key = display_id # The key is the Task ID

                    # LOGIC PATH 2: The rule is global, with no ID to capture (e.g., RECOGNIZER_DB_SAVE_TIME)
                    else:
                        pending_key = f"global_{event_name}"

                    # Now that we have a key, add the event to the pending dictionary
                    if pending_key and pending_key not in pending_events[event_name]:
                        start_time, _ = parse_line(line)
                        if start_time:
                            # Store the key, the start time, the line number, and the clean display ID
                            pending_events[event_name][pending_key] = (start_time, i, display_id)



    # --- Write CSV and Plot ---
    if not completed_events:
        print("\nWarning: No complete timing events were found based on the defined rules.")
        return

    print(f"\nWriting analysis to '{OUTPUT_CSV_FILE}'...")
    completed_events.sort(key=lambda x: x['Start Time'])

    with open(OUTPUT_CSV_FILE, 'w', newline='', encoding='utf-8') as f:
        fieldnames = ['Event Name', 'Event ID', 'Start Time', 'End Time', 'Duration (ms)', 'Start Line', 'End Line']
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(completed_events)

    print(f"✅ Analysis complete! Results saved to '{OUTPUT_CSV_FILE}'.")
    plot_gantt_chart(completed_events)
    print("\n--- Performance Summary ---")
    completed_events.sort(key=lambda x: (x['Event ID'], x['Start Time']))
    for event in completed_events:
        print(f"ID: {event['Event ID']:<12} | Event: {event['Event Name']:<35} | Duration: {event['Duration (ms)']:>8} ms")


if __name__ == '__main__':
    main()

